# Each page blueprint must have a title, the title may be different from the file name
# This default blueprint is used to display a page in the Panel whenever a custom page blueprint is missing.
title: Simple Page

# Each page can have an icon that is shown in page listings when no preview image is available.
icon: 📝

# Custom descriptions of page statuses depending on use case
# More about page statuses: https://getkirby.com/docs/reference/panel/blueprints/page#statuses
status:
  draft: true
  unlisted:
    label: Hidden Page
    text: The page is not listed in the main menu
  listed:
    label: Menu Page
    text: The page is listed in the main menu

# Content area width 2 columns and 3 sections: fields, pages, and files
# Columns: https://getkirby.com/docs/guide/blueprints/layout#defining-columns
columns:
  main:
    width: 2/3
    sections:
      # Fields section: https://getkirby.com/docs/reference/panel/sections/fields
      fields:
        type: fields
        fields:
          subheadline:
            type: text
          is_featured_on_choice:
            label: Include this page on the Choice page?
            type: toggle
            default: false
            text:
              - "No"
              - "Yes"
          layout:
            label: Layout
            type: layout
            fieldsets:
              - text
              - heading
              - quote
              - list
              - image
              - gallery
              - video
              - line
              - table
              - code
              - archive-reference
            layouts:
              - "1/1"
              - "1/2, 1/2"
              - "1/3, 1/3, 1/3"
  sidebar:
    width: 1/3
    sections:
      # Pages section: https://getkirby.com/docs/reference/panel/sections/pages
      pages:
        type: pages
        template: default
      # Files section: https://getkirby.com/docs/reference/panel/sections/files
      files:
        type: files
